watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ['*'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 1000   
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: true
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 40
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: [
        "gpu",
        "cpu",
        "memory",
        "download",
        "upload",
      ]
      center: [
        "cava"
      ]
      right: [
        "media",
        "volume",
        "notifications",
        "battery"
      ]
widgets:
  download:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "<span>\uf0ab</span>{download_speed}"
      speed_unit: 'bytes'
      update_interval: 1000
      max_label_length_align: right
      max_label_length: 10
      callbacks:
        on_left: 'do_nothing'
        on_middle: 'do_nothing'
        on_right: 'do_nothing'
  upload:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "<span>\uf0aa</span>{upload_speed}"
      speed_unit: 'bytes'
      update_interval: 1000
      max_label_length_align: right
      max_label_length: 10
      callbacks:
        on_left: 'do_nothing'
        on_middle: 'do_nothing'
        on_right: 'do_nothing'
  gpu:
    type: "yasb.gpu.GpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[utilization]}%"
      update_interval: 2000
      callbacks:
        on_left: 'do_nothing'
        on_middle: 'do_nothing'
        on_right: 'do_nothing'
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      update_interval: 2000
      callbacks:
        on_left: 'do_nothing'
        on_middle: 'do_nothing'
        on_right: 'do_nothing'
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_outof}"
      update_interval: 10000
      callbacks:
        on_left: 'do_nothing'
        on_middle: 'do_nothing'
        on_right: 'do_nothing'
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 12
      gradient: 0
      reverse: 0
      sensitivity: 100
      foreground: "#ffffff"
      gradient_color_1: '#119756'
      gradient_color_2: '#969711'
      gradient_color_3: '#971211'
      bars_number: 8
      bar_spacing: 2
      bar_width: 6
      sleep_timer: 0
      hide_empty: true
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{artist} - {title}"
      label_alt: "{title}"
      hide_empty: true
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "toggle_play_pause"
        on_right: "toggle_label"
      max_field_size:
        label: 35
        label_alt: 35
      show_thumbnail: true
      controls_only: false
      controls_left: false
      controls_hide: true
      thumbnail_edge_fade: true
      thumbnail_padding: 32
      scrolling_label:
        enabled: false
        update_interval_ms: 50
        style: "left"
        separator: " "
        label_padding: 2
        ease_slope: 20
        ease_pos: 0.8
        ease_min: 0.5
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"
      media_menu:
        blur: false
        round_corners: true
        round_corners_type: "normal"
        border_color: "None"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        thumbnail_corner_radius: 4
        thumbnail_size: 80
        max_title_size: 60
        max_artist_size: 20
        show_source: true
      media_menu_icons:
        play: "\ue768"
        pause: "\ue769"
        prev_track: "\ue892"
        next_track: "\ue893"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{level}"
      mute_text: "Mute"
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "toggle_mute"
      audio_menu:
        blur: false
        round_corners: true
        round_corners_type: "normal"
        border_color: "None"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
      container_padding:
        top: 0
        left: 2
        bottom: 0
        right: 2
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span> {count}"
      hide_empty: false
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "toggle_label"
      container_padding:
        top: 0
        left: 4
        bottom: 0
        right: 4
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span> {percent}%"
      label_alt: " time: {time_remaining}"
      hide_unsupported: true
      charging_options:
        icon_format: "{charging_icon}"
      status_thresholds:
        critical: 10
        low: 25
        medium: 75
        high: 95
        full: 100
      status_icons:
        icon_charging: "\uf0e7"
        icon_critical: "\uf244"
        icon_low: "\uf243"
        icon_medium: "\uf242"
        icon_high: "\uf241"
        icon_full: "\uf240"
      callbacks:
        on_left: 'do_nothing'
        on_middle: 'do_nothing'
        on_right: 'do_nothing'